name: personal_assistant
description: A personal expense tracking assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # Authentication & Google Services
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  
  # HTTP requests
  http: ^1.1.0
  dio: ^5.3.2
  
  # Voice & Speech
  speech_to_text: ^6.6.0
  
  # OpenAI Integration
  dart_openai: ^5.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date & Time
  intl: ^0.18.1
  
  # JSON handling
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env 